version: '2'
services:
  app:
    image: rhinocrones/app:1
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
  mypostgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=postgres

