spring:
  datasource:
    url: jdbc:postgresql://mypostgres:5432/postgres
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  jackson:
    time-zone: GMT+03